apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hpa-example01
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/karapet-andreasyan/gitops-level-2.git
    targetRevision: HEAD
    path: ./custom-diff/01-with-hpa
   
  destination:
    server: https://kubernetes.default.svc
    namespace: example01

  # Sync policy
  syncPolicy:
    syncOptions:
      - CreateNamespace=true  
   
