---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-deployment
spec:
  template:
    spec:
      containers:
      - name: webserver-simple
        image: ghcr.io/karapet-andreasyan/gitops-level-2:1.0
